// The realm's soundtrack for the jukebox (Music tab): every area theme, named, in one warm score.
// Export interface matches scripts/lib/music-tracks.js exactly

var TRACKS = [
  { name: "Realm of the Nine I", url: "/cdn/moodboard-painterly-fantasy/music-majestic-fantasy-main-theme-solo-horn-rising-strings-choir-swell-loop.mp3", duration: 150 },
  { name: "Realm of the Nine II", url: "/cdn/moodboard-painterly-fantasy/music-wistful-fantasy-title-theme-solo-cello-harp-warm-strings-distant-choir-loop.mp3", duration: 150 },
  { name: "Realm of the Nine III", url: "/cdn/moodboard-painterly-fantasy/music-golden-dusk-fantasy-overture-french-horn-harp-strings-slow-rise-loop.mp3", duration: 150 },
  { name: "A Hero Wakes I", url: "/cdn/moodboard-painterly-fantasy/music-gentle-hopeful-fantasy-harp-celesta-soft-strings-hero-awakening-loop.mp3", duration: 150 },
  { name: "A Hero Wakes II", url: "/cdn/moodboard-painterly-fantasy/music-tender-fantasy-character-select-celesta-harp-soft-cello-music-box-loop.mp3", duration: 150 },
  { name: "Lantern’s Reach I", url: "/cdn/moodboard-painterly-fantasy/music-warm-medieval-village-lute-recorder-hand-drum-afternoon-loop.mp3", duration: 150 },
  { name: "Lantern’s Reach II", url: "/cdn/moodboard-painterly-fantasy/music-cozy-fantasy-town-square-lute-fiddle-soft-harp-warm-strings-golden-afternoon-loop.mp3", duration: 150 },
  { name: "Lantern’s Reach III", url: "/cdn/moodboard-painterly-fantasy/music-lantern-lit-fantasy-tavern-evening-mandolin-tin-whistle-cello-loop.mp3", duration: 150 },
  { name: "The Briarwild I", url: "/cdn/moodboard-painterly-fantasy/music-enchanted-forest-wooden-flute-plucked-harp-mysterious-strings-loop.mp3", duration: 150 },
  { name: "The Briarwild II", url: "/cdn/moodboard-painterly-fantasy/music-sunlit-fantasy-woodland-harp-alto-flute-pizzicato-strings-celesta-loop.mp3", duration: 150 },
  { name: "The Briarwild III", url: "/cdn/moodboard-painterly-fantasy/music-quiet-old-forest-fantasy-solo-cello-wooden-flute-soft-pads-loop.mp3", duration: 150 },
  { name: "Saltmere Shore I", url: "/cdn/moodboard-painterly-fantasy/music-seaside-folk-accordion-fiddle-gentle-waves-sea-shanty-calm-loop.mp3", duration: 150 },
  { name: "Saltmere Shore II", url: "/cdn/moodboard-painterly-fantasy/music-wistful-fantasy-harbour-tin-whistle-harp-soft-strings-gentle-tide-loop.mp3", duration: 150 },
  { name: "Saltmere Shore III", url: "/cdn/moodboard-painterly-fantasy/music-bright-fantasy-seaside-morning-fiddle-acoustic-guitar-light-percussion-loop.mp3", duration: 150 },
  { name: "Sorrowfen I", url: "/cdn/moodboard-painterly-fantasy/music-eerie-misty-swamp-low-cello-drones-distant-chimes-melancholy-loop.mp3", duration: 150 },
  { name: "Sorrowfen II", url: "/cdn/moodboard-painterly-fantasy/music-melancholy-fantasy-marsh-solo-viola-hammered-dulcimer-low-pads-loop.mp3", duration: 150 },
  { name: "Sorrowfen III", url: "/cdn/moodboard-painterly-fantasy/music-mysterious-fantasy-wetland-bass-clarinet-harp-slow-mist-loop.mp3", duration: 150 },
  { name: "Cinderhold I", url: "/cdn/moodboard-painterly-fantasy/music-heroic-dwarven-forge-deep-brass-war-drums-anvil-hits-loop.mp3", duration: 150 },
  { name: "Cinderhold II", url: "/cdn/moodboard-painterly-fantasy/music-proud-fantasy-mountain-hold-low-horns-steady-drums-cello-ostinato-loop.mp3", duration: 150 },
  { name: "Cinderhold III", url: "/cdn/moodboard-painterly-fantasy/music-warm-fantasy-forge-town-hammered-dulcimer-brass-choir-hum-loop.mp3", duration: 150 },
  { name: "Starfall Eyrie I", url: "/cdn/moodboard-painterly-fantasy/music-ancient-arcane-ruins-ethereal-choir-glass-harmonica-slow-pads-loop.mp3", duration: 150 },
  { name: "Starfall Eyrie II", url: "/cdn/moodboard-painterly-fantasy/music-luminous-fantasy-starlit-eyrie-celesta-harp-high-strings-soft-choir-loop.mp3", duration: 150 },
  { name: "Starfall Eyrie III", url: "/cdn/moodboard-painterly-fantasy/music-ancient-fantasy-observatory-glass-bells-slow-strings-ethereal-voice-loop.mp3", duration: 150 },
  { name: "The Open March I", url: "/cdn/music-instrumental-fantasy-adventure-orchestral.mp3", duration: 150 },
  { name: "The Open March II", url: "/cdn/moodboard-painterly-fantasy/music-sweeping-fantasy-open-road-strings-french-horn-harp-travel-loop.mp3", duration: 150 },
  { name: "The Open March III", url: "/cdn/moodboard-painterly-fantasy/music-gentle-fantasy-rolling-hills-acoustic-guitar-flute-soft-strings-loop.mp3", duration: 150 },
  { name: "Ashen Close I", url: "/cdn/moodboard-gothic-horror/music-ashen-close-graveyard-dark-gothic-solo-cello-music-box-distant-church-bell-dread-loop.mp3", duration: 150 },
  { name: "Ashen Close II", url: "/cdn/moodboard-gothic-horror/music-mournful-gothic-fantasy-graveyard-low-cello-harp-faint-choir-loop.mp3", duration: 150 },
  { name: "Greyspine Pass I", url: "/cdn/moodboard-painterly-fantasy/music-frozen-mountain-pass-lonely-low-horn-icy-glass-pads-slow-taiko-wind-loop.mp3", duration: 150 },
  { name: "Greyspine Pass II", url: "/cdn/moodboard-painterly-fantasy/music-cold-fantasy-highland-pass-solo-violin-low-strings-sparse-bells-loop.mp3", duration: 150 },
  { name: "Ashfall Reaches I", url: "/cdn/moodboard-painterly-fantasy/music-scorched-ash-desert-duduk-lament-frame-drum-low-drone-heat-haze-loop.mp3", duration: 150 },
  { name: "Ashfall Reaches II", url: "/cdn/moodboard-painterly-fantasy/music-sunbaked-fantasy-wasteland-oud-frame-drum-low-strings-loop.mp3", duration: 150 },
  { name: "Steel Drawn I", url: "/cdn/moodboard-painterly-fantasy/music-tense-fantasy-battle-war-drums-low-brass-staccato-strings-loop.mp3", duration: 150 },
  { name: "Steel Drawn II", url: "/cdn/moodboard-painterly-fantasy/music-urgent-fantasy-skirmish-taiko-low-brass-driving-cello-ostinato-loop.mp3", duration: 150 },
  { name: "Steel Drawn III", url: "/cdn/moodboard-painterly-fantasy/music-heroic-fantasy-fight-war-drums-strings-horn-calls-loop.mp3", duration: 150 },
  { name: "Hollowcrypt", url: "/cdn/moodboard-gothic-horror/music-hollowcrypt-candlelit-vault-low-choir-slow-bells.mp3", duration: 150 },
  { name: "The Drowned Bell", url: "/cdn/moodboard-gothic-horror/music-drowned-bell-underwater-choir-muffled-bells-slow-dread-loop.mp3", duration: 150 },
  { name: "Root Archive", url: "/cdn/moodboard-painterly-fantasy/music-root-archive-ancient-underground-forest-low-woodwinds-heartbeat-drum-loop.mp3", duration: 150 },
  { name: "The Pale Choir", url: "/cdn/moodboard-gothic-horror/music-pale-choir-raid-cathedral-organ-dark-choir-epic-loop.mp3", duration: 150 },
  { name: "Emberheart Caldera", url: "/cdn/moodboard-painterly-fantasy/music-emberheart-caldera-raid-volcanic-war-drums-brass-choir-epic-loop.mp3", duration: 150 },
  { name: "The Ninth Assembly", url: "/cdn/moodboard-painterly-fantasy/music-assembly-of-the-ninth-finale-cosmic-choir-strings-bells-epic-loop.mp3", duration: 150 },
];

module.exports = { TRACKS: TRACKS };
