// The game's update version: bump this line with each release (0.47.6: guild banner over the Hall of Banners). Drawn only on the main menu, settings and pause screens.
var GAME_VERSION = '0.47.73 Alpha';
// The Herald of the Realm on the main menu reads these, newest first: [version, title, note, optional /cdn/ art]. Add a row with each bump.
var PATCH_NOTES = [
  ['v0.47.73', 'Every Foe Its Weather', 'Seven more enemy camps carry an aura. Bloodmarked Raiders kick up dust with red rage-sparks, Deepgrove Raiders trail forest dust and leaves, Court Brine-Takers smoke violet with orbiting motes, the Mirelurker steams and drips under a cold blue glow, Phantom Currents drip sea mist, Tether-Spirits shed falling links of light, and the Inkbound Archivists bleed black ink and drifting runes.'],
  ['v0.47.72', 'Soot and Cinder', 'The Soot-Ghoul Breakers in the Cinderhold quarry now smoke as they work, spitting cinders with a faint ember glow at the face cage. Gorrath, the Pit-Warden, stands in a rust-red forge haze, bone dust drifting off his crown and embers rising off his cleaver arm.'],
  ['v0.47.71', 'Grimfang Roars', 'Grimfang, the Thorn Alpha, now smoulders: red thorn dust and embers rise off him and a low ember glow follows him through the den. When he spots you he lets out a deep roar that shakes the ground and calls every idle wolf in the den down on you.'],
  ['v0.47.70', 'The Pack Calls', 'The first Briar Wolf to catch your scent now throws its head back and howls, and every idle wolf within earshot breaks off and runs at you with it. Walk the Briarwild road carefully.'],
  ['v0.47.69', 'Every Homecoming Has Its Weather', 'All six homecoming bosses now carry their own aura. Gharn the Unbanked drips molten embers in a heat haze, Captain Merrow trails sea mist and seawater, Hollowsong sheds glowing spores and dead leaves, the Unbraided hums with marsh flies over murk, and the Star That Answered spins violet motes and shards around her. Far bosses put theirs on the moment they wake.'],
  ['v0.47.68', 'The Lampless Smoulders', 'Reeve Ashcombe now carries his own dark: soot pours off his shoulders, cold blue embers lift around him, ash drifts down, and his dead lantern smokes with a pale glow at his hip. It all goes out when he is laid to rest, and comes back when he rises again.'],
  ['v0.47.67', 'The Briar Pack Grows Wild', 'Briar Wolves are rebuilt meaner: a shaggy black mane of over a hundred fur tufts, a ragged back and a hanging belly fringe, starved bone ribs showing through the flanks, and thorned briar vines strangling their bodies and winding up their forelegs.'],
  ['v0.47.66', 'Nights in the March', 'The sun over Lantern March finally moves: long golden evenings, then a short starlit night, one full day each hour. After sunset the meadows fill with crickets, owls call from the pines, nightjars churr on the heath, and the Reach goes quiet but for its hearths.'],
  ['v0.47.65', 'Shadow Rend', 'Shades learn a fourth art on key 4: Shadow Rend. Blink 8 m ahead through violet shadow, cutting every foe along the path. Cast from the Veil, every cut lands as an Ambush, and you come out of it with an Ambush window open for your next Strike. Every calling now has four abilities.'],
  ['v0.47.64', 'Earthsplitter', 'Vanguards learn a fourth blow on key 4: Earthsplitter. The blade slams down and a molten fissure tears 9 m ahead, striking every foe on the line, hurling them back and slowing them. Heavy Strike now cleaves up to four foes in front of you. Key 4 now works for every calling (Cinderfall and Rain of Thorns could not be cast before this).'],
  ['v0.47.63', 'Rain of Thorns', 'Pathfinders learn a fourth shot on key 4: Rain of Thorns. One arrow goes up high, a green ring marks the ground, then three waves of arrows hammer everything within 4.5 m. Brambles grow where they land and slow anything inside by half for 4 s. 14 s cooldown.'],
  ['v0.47.62', 'Cinderfall', 'Arcanists learn a fourth spell on key 4: Cinderfall calls a falling star down on your target. A warning ring burns on the ground, the star streaks in, and the blast hits everything within 4 m for heavy fire damage, scattering burning rock and leaving the earth scorched. 12 s cooldown.'],
  ['v0.47.61', 'Know Thyself', 'The Character page (C) now shows your real power under the paper doll: XP to your next level, total damage on every ability and where it comes from (level, gear, training, talents), cooldown haste, max health, and your specialization at a glance.'],
  ['v0.47.60', 'Paths of Mastery', 'Talent trees for every discipline: three specializations each (Bulwark, Warbringer and Lanternguard for the Vanguard; Ember, Rime and Aether for the Arcanist; Marksman, Wildrunner and Briarward for the Pathfinder; Nightblade, Duskwalker and Veilborn for the Shade). You earn a point every 5 levels, and each pick adds damage, faster cooldowns or max health. Reset any time. Press N.'],
  ['v0.47.59', 'Hearth & Eave', 'Every cottage and hall in the March gains its close-up finish: barge boards along the gables, rafter tails under the eaves, flower boxes under the windows, iron strap hinges and a ring on each door.'],
  ['v0.47.58', 'Deeper Woods', 'Up close, the March\'s oaks now grow forking, tapered limbs over flared roots with twice the leaf clusters; pines carry fuller tiers; dead trees reach out with gnarled, branching arms.'],
  ['v0.47.57', 'Clear Eyes', 'The March is drawn crisper: finer edges and detail sharpened back after smoothing, the film grain nearly gone, a softer bloom that no longer haloes lamps. The title screen\'s reflections and glow blur less.'],
  ['v0.47.56', 'Teeth in the Dark', 'The beasts and brigands around Lantern\'s Reach have turned. Briar wolves run soot-black now, a ridge of bone thorns down their spines, fangs bared and eyes like embers, and Grimfang the Thorn Alpha, half again their size, leads them from the den. The quarry thieves are hollow cultists in chains and bone charms, the bridge raiders scarred brutes in horned iron, the drill crew soot-ghouls with burning eyes. And at the bottom of the quarry, between two braziers, Gorrath the Pit-Warden waits with his cleaver. South of the Reach, Reeve Ashcombe the Lampless walks again, gaunt and burnt black, a dead lantern smoking on his chain.'],
  ['v0.47.55', 'Clean Swings', 'Quarry scavengers no longer freeze mid-swing: every strike, flinch and toll blends back into their stride. Their blows kick up dust and grit, and a guarded block throws sparks.'],
  ['v0.47.54', 'Dread Below', 'Hollowcrypt is darker and more drained now, with grain, a closing vignette and warm candle pools. Wolf paws step with the ground instead of sliding, and the title gate glows with traced light.'],
  ['v0.47.53', 'Awakening', 'The Lantern March wakes under a new sky: true-to-life light, volumetric clouds, sun-lit mist in the valleys and a filmic grade. Wolves now walk, gallop, lunge and fall with far smoother motion.'],
  ['v0.47.52', 'The woods remember', 'Firebolt burns with a living flame and a heat shimmer and scorches the ground where it lands; Frost Shard leaves rime behind. Wisps, fireflies and pollen now drift through the Briarwild, Deepgrove, Deepwood, Petalfall, Thornhollow, Sorrowfen and Velthraen, each wood in its own colour.'],
  ['v0.47.51', 'Towns that breathe', 'Every hearth town has its own sound now: glass chimes in Thornhollow, creaking boardwalks and frogs in Reedhaven, cliff wind and banners at Starfall Eyrie, gulls and rigging at Gullrest, distant hammers in Cinderhold.'],
  ['v0.47.50', 'Steel and string', 'The Vanguard\'s sword sings through the air, its heavy blow comes with a grunt and a deep rush, raising the guard thumps a shield into place, and the Pathfinder\'s volley looses three strings at once.'],
  ['v0.47.49', 'Every step heard', 'A jump now rustles leather and catches a breath, a long fall lands with a thump of boots and gear, and gravel roads crunch underfoot.'],
  ['v0.47.48', 'The Realm Sings', 'Every land now has its own playlist of two or three songs in one warm score, the title screen too, and the Music tab holds the whole soundtrack. Emberwell and the Star Pool sing their own lands now.'],
  ['v0.47.47', 'Hidden Places', 'Your quest log (L) now keeps a tally of the March\'s hidden places, with a riddle for each one you have not found.'],
  ['v0.47.46', 'The Star Pool', 'East of Starfall Eyrie, on a shelf of the mountain, a still pool holds the stars even by day. Five pale stones keep watch. So did someone else, once.'],
  ['v0.47.45', 'No beast enters the water', 'Wolves and raiders will not follow you into Emberwell Spring. Run for the steam and they break off at the stones.'],
  ['v0.47.44', 'A warm soak', 'Step into the water at Emberwell Spring and your wounds mend fast, even with wolves at your back.'],
  ['v0.47.43', 'Emberwell Spring', 'West of Cinderhold, a little off the road, a hot spring steams between old stones. A miner left his strongbox by the water and never came back for it.'],
  ['v0.47.42', 'A name in the pines', 'Step into Petalfall Hollow and its name rises over the glade, with a fanfare the first time you find it.'],
  ['v0.47.41', 'Signs on the shrines', 'Each wayside shrine now hangs a gilt sign you can read from the road, so travelers know where to kneel for the Wayfarer\'s Blessing.'],
  ['v0.47.40', 'A lighter gate', 'The main menu now stands before the in-world interface downloads; the rest arrives quietly a moment later.'],
  ['v0.47.39', 'Petalfall Hollow', 'Somewhere in the thornwood west of Lantern\'s Reach, a ring of blossom trees hides a spring, six old standing stones and a fairy ring. Someone left an offering box there. Find it.', '/cdn/value.a3b7d175b8f2989f4561896afd914517e6f45914e600f2a1ef647bd38b46eec1.png'],
  ['v0.47.38', "The Wayfarer's Blessing", "Kneel at any wayside shrine on the town roads (E) for the Wayfarer's Blessing: 20% faster travel for five minutes, golden motes at your heels.", '/cdn/value.a3b7d175b8f2989f4561896afd914517e6f45914e600f2a1ef647bd38b46eec1.png'],
  ['v0.47.36', 'Wayside Shrines', 'A small candlelit shrine under a red shingle roof, a bench beside it, now waits along the road out of every race town. Walk close and you hear its candles crackle and its chimes stir.', '/cdn/value.a3b7d175b8f2989f4561896afd914517e6f45914e600f2a1ef647bd38b46eec1.png'],
  ['v0.47.35', 'Lanterns on the Roads', 'Iron lantern posts now line the first stretch of road out of every race town, so the way home glows at dusk.', '/cdn/value.a3b7d175b8f2989f4561896afd914517e6f45914e600f2a1ef647bd38b46eec1.png'],
  ['v0.47.34', 'Arches of the Hearths', 'Every race town now greets the road with a flowering arch and a hanging lantern: ember gold at Cinderhold, sea blue at Gullrest, fen violet at Reedhaven, star white at Starfall Eyrie.', '/cdn/value.a3b7d175b8f2989f4561896afd914517e6f45914e600f2a1ef647bd38b46eec1.png'],
  ['v0.47.33', 'Thornhollow in Bloom', 'Seven flower beds now fill the bare clearings around Thornhollow, and a rose arch with a hanging lantern spans the road into town.', '/cdn/value.a3b7d175b8f2989f4561896afd914517e6f45914e600f2a1ef647bd38b46eec1.png'],
  ['v0.47.27', 'Green Rise', 'The blossom hamlet now sits on a gentle green rise above the tideline, deep meadow grass and wildflowers instead of wet sand.', '/cdn/value.a3b7d175b8f2989f4561896afd914517e6f45914e600f2a1ef647bd38b46eec1.png'],
  ['v0.47.26', 'The Blossom Hamlet', 'Four cottages now stand on the Reedhaven road, each in a ring of roses and lupines, a lamp over every door. The last of the town kit is placed too: crates, red banners and a farm gate in Lantern\'s Reach.', '/cdn/value.a3b7d175b8f2989f4561896afd914517e6f45914e600f2a1ef647bd38b46eec1.png'],
  ['v0.47.24', 'Petals on the Wind', 'Blossom petals now drift across the March roads and Thornhollow, and fireflies glow low over the flower beds of every hearth town.', '/cdn/value.a3b7d175b8f2989f4561896afd914517e6f45914e600f2a1ef647bd38b46eec1.png'],
  ['v0.47.23', 'Every Hearth in Bloom', 'Each race town now wears its own flowers: rose and violet at Thornhollow, ember gold at Cinderhold, sea blue at Gullrest, fen violet at Reedhaven, star white at Starfall Eyrie.', '/cdn/value.a3b7d175b8f2989f4561896afd914517e6f45914e600f2a1ef647bd38b46eec1.png'],
  ['v0.47.22', 'The March in Bloom', 'Blossom trees and wildflower meadows now line the roads out of Lantern\'s Reach.', '/cdn/value.a3b7d175b8f2989f4561896afd914517e6f45914e600f2a1ef647bd38b46eec1.png'],
  ['v0.47', 'Wings over the March', 'Eleven gryphon roosts now link the continent. Walk near one to learn it, press E to fly. The Ninth Veil and the Ashfall Reaches wait at the far edges.', '/cdn/value.9b81f41b857bd952a2ae562a55e5b84d5eb6137b07dee8760b7cc32d97bd68f0.png'],
  ['v0.47', 'The Deepgrove Bounty', 'A lit board west of Rootwake Glade pays for Scab\'s raiders. Level 8 and up.', '/cdn/value.6489d07ac1164f457c728992a582ec1e52cb7ce0d2e3e0b4726fae264c3ebd86.png'],
  ['v0.46', 'Wells of the March', 'Draw a bucket at any town well and drink to heal over time.'],
  ['v0.46', 'Party Finder & Banner Vale', 'Queue for dungeons, raids and the 5v5 banner battleground from any town board.', '/cdn/value.b076587b8d0ebb04368c665fb66c1a3d0e1303b8695e64a49188e8c8e5ae0436.png'],
];
var GAME_TITLE = 'WHISPERS: Realm of the Nine';
function versionTag(extra) {
  return '<div style="position:fixed;left:50%;bottom:8px;transform:translateX(-50%);z-index:9999;pointer-events:none;'
    + 'font:500 11px/1 Cinzel,Palatino,Georgia,serif;letter-spacing:1.5px;color:rgba(232,217,181,.55);text-shadow:0 1px 2px #000;white-space:nowrap;' + (extra || '') + '">'
    + GAME_TITLE + ' &middot; v' + GAME_VERSION + '</div>';
}
module.exports = { GAME_VERSION: GAME_VERSION, GAME_TITLE: GAME_TITLE, versionTag: versionTag, PATCH_NOTES: PATCH_NOTES };
